# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine
GAMEPROJECTFILE =/home/kevinp5/School/cs_498/MP1/MP1.uproject

TARGETS = \
	MP1-Linux-DebugGame  \
	MP1-Linux-Shipping  \
	MP1 \
	MP1Editor-Linux-DebugGame  \
	MP1Editor-Linux-Shipping  \
	MP1Editor \
	UE4Editor-Linux-DebugGame  \
	UE4Editor-Linux-Shipping  \
	UE4Editor \
	UE4Game-Linux-DebugGame  \
	UE4Game-Linux-Shipping  \
	UE4Game\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass

StandardSet: RequiredTools UnrealFrontend UE4Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UE4Editor-Linux-Debug


MP1-Linux-DebugGame:
	 $(PROJECTBUILD) MP1 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MP1-Linux-Shipping:
	 $(PROJECTBUILD) MP1 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MP1:
	 $(PROJECTBUILD) MP1 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MP1Editor-Linux-DebugGame:
	 $(PROJECTBUILD) MP1Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MP1Editor-Linux-Shipping:
	 $(PROJECTBUILD) MP1Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MP1Editor:
	 $(PROJECTBUILD) MP1Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-DebugGame:
	 $(BUILD) UE4Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-Shipping:
	 $(BUILD) UE4Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor:
	 $(BUILD) UE4Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-DebugGame:
	 $(BUILD) UE4Game Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-Shipping:
	 $(BUILD) UE4Game Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game:
	 $(BUILD) UE4Game Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
